### ISSUE TITLE
Why did legal have a problem with non-chef links in the OSS Distribution guidelines?

### ISSUE THREAD

**Issue by lrosenman** [chef/chef-oss-practices#222]
# Describe the problem

in commit https://github.com/chef/chef-oss-practices/pull/220/commits/75840646bd0827d11050ddb2747dda7730cba26d the link to the InSpec community project was removed "per Chef Legal".  What problem did/does Chef Legal have with outside links to community projects?

**Comment by nellshamrell** [comment]
Hi @lrosenman - while I understand the curiousity behind this question and understand you raising it, the honest answer is I ran the distribution guidelines by our legal team and they asked me to remove it and I did so without asking any questions. Closing this.

**Comment by nellshamrell** [comment]
@lrosenman - upon reading back my above comment, I realize it sounded harsh - let me get back to you on this.

**Comment by cscobie** [comment]
It is true that Chef's legal department passed on the recommendation to remove the link, but that decision came out of a conversation between myself and our legal team and I was the one that recommended the removal of the link. My logic was that in an important policy reference document, I was not comfortable with referencing a link outside Chef's control.

**Comment by lrosenman** [comment]
If we're supposed to be working as a community, we should, in my opinion, be able to reference other community efforts as examples.   If need be, put a disclaimer that any link(s) outside of Chef Software, inc.'s control are not under any liability from Chef Software, Inc.  It makes it hard to collaborate if we can't link out of these documents to non-chef resources.

**Comment by robbkidd** [comment]
@nellshamrell and I have some ideas that includes both linking and disclaiming as you suggest, @lrosenman. We'll follow up during US work hours!

**Comment by cscobie** [comment]
@lrosenman Yes. I agree. Collaboration means being able to reference each other’s work. And in the normal course of business this is all good. We are not trying to create an island that is only Chef.
However, this particular document (and probably a few others) are representative of a different class of documentation. This is a policy document that I wouldn’t normally use Github as a storage platform for and therefore I will apply different heuristics to it than others. And in this case one of those heuristics is that I would prefer that it didn’t contain links to external information where Chef has no knowledge of the current/future change control process for that content. I am fine with it being here but will be a little more picky about the end state of the document because I expect it to be a durable guide for the community and public at large on Chef’s policy interpretation with respect to alternate distributions of software. Let’s not take this particular document as a representation of cross repo collaboration at large. Link away (it’s the Internet) but just not on this one.

**Comment by nellshamrell** [comment]
This repo is intended to be a place for us to collaborate. We certainly want to not only acknowledge but highlight our community's efforts.

What if we were to:

1) Create a new directory at the root of this repo called "distributions"
2) Move the distributions policy doc to this directory
3) Create a new doc within that directory that will list distributions with links to their project pages (the doc will include a disclaimer that the content on those pages is outside of Chef's control).
4) The policy page will link to the new list of distributions (that list is under Chef's control)

**Comment by nellshamrell** [comment]
It's getting late in the work day here, but let's follow up on this tomorrow.

**Comment by Tensibai** [comment]
@cscobie the link was pointing to a merge request, so mostly a git diff change...

I may understand not willing to link to a wiki page, but declining collaborative work showcasing what your ask community to do is not productive in my opinion.

**Comment by robbkidd** [comment]
I think we need to find a place to showcase collaboration that isn't in what amounts to a policy document from Chef Software. I like Nell's proposal to expand the current document to a section in this repo where the policy document can focus on guidelines and other pages there can link-offsite-with-disclaimers to specific distributions and/or efforts.

**Comment by ramereth** [comment]
@nellshamrell that sounds reasonable to me

**Comment by nellshamrell** [comment]
Going to implement the above solution on Monday morning. What are the best links for the community repos? I could link to https://gitlab.com/cc-build, but there's not a lot of context at that landing page, where would people suggest we link for the various projects in our distribution list?

**Comment by ramereth** [comment]
@nellshamrell I'll work on updating the project description so that it's more apparent what we currently have by Monday.

**Comment by nellshamrell** [comment]
This week I will create the list of distributions to include in this repo and will update this issue when I have a pull request open.

**Comment by bennyvasquez** [comment]
Closing since Nell fixed this in https://github.com/chef/chef-oss-practices/pull/229
