### ISSUE TITLE
What is the status of habitat builder depot?

### ISSUE THREAD

**Issue by Tensibai** [chef/chef-oss-practices#224]
## Detailed Description
Chef software have all plan t be build and distributed from habitat builder depot, for automate2 specifically this is the only packaging system. 

Considering a community distribution of Chef's products and more generally OSS softwares, does hosting public packages on habitat builder depot needs a commercial license ?

**Comment by cscobie** [comment]
I will do my best to unpack this here:
- Chef will continue to take community contributions of Habitat software packages (i.e. core plans) and host them in the Chef hosted cloud builder depot. However, only Chef's commercial customers will be eligible to connect to the Chef hosted builder depot (directly or via an on premise depot). This is not enforced today but is in our plans.
- In order to facilitate a community distribution of Habitat, Chef will support a community hosted builder instance by providing a "mirror" feed of the public assets in the Chef hosted builder depot. Chef will not host a community builder depot, the community will be responsible for that but Chef will work with the community to feed the common public packages to the community builder depot.

Summary - assuming that a community distribution of Chef Habitat exists, and the community offers a hosted builder depot, Chef will provide a technical implementation so that we can stay synced in public packages.

**Comment by Tensibai** [comment]
To ensure I understood that properly:bldr.habitat.sh is only usable by commercial customers.Contributions to core plans are still welcome (as PR on github as today I assume) Existing origins not from commercial customers will be stripped from bldr.habitat.sh? Le 29 mai 2019 20:17, Corey Scobie <notifications@github.com> a écrit :I will do my best to unpack this here:
Chef will continue to take community contributions of Habitat software packages (i.e. core plans) and host them in the Chef hosted cloud builder depot. However, only Chef's commercial customers will be eligible to connect to the Chef hosted builder depot (directly or via an on premise depot). This is not enforced today but is in our plans.In order to facilitate a community distribution of Habitat, Chef will support a community hosted builder instance by providing a "mirror" feed of the public assets in the Chef hosted builder depot. Chef will not host a community builder depot, the community will be responsible for that but Chef will work with the community to feed the common public packages to the community builder depot.
Summary - assuming that a community distribution of Chef Habitat exists, and the community offers a hosted builder depot, Chef will provide a technical implementation so that we can stay synced in public packages.

**Comment by cscobie** [comment]
Answers in the same order as asked:

- bldr.habitat.sh is only usable by commercial customers.
Not true today but you can expect that to be true at some point in the future. We don’t have a timeline around this transition but will be working on it this year.

- Contributions to core plans are still welcome (as PR on github as today I assume) 
Correct.

- Existing origins not from commercial customers will be stripped from bldr.habitat.sh?
Transition plan is still being worked but yes, we will expect non-commercial origins on bldr.habitat.sh to migrate at some point. We will work with users to smooth that migration and ensure integrity of anything they have deployed.

**Comment by nellshamrell** [comment]
This appears to have been answered, so I'm going to go ahead and closed this, but if you have further questions @Tensibai feel free to re-open this issue.

**Comment by Tensibai** [comment]
@nellshamrell just one, should we close if we thing we have an answer or let you handle the closing?
